import gameDates from './gameDates';

const players = [
	{
		name: 'German',
		gender: 'M',
		position: 'left back',
		secondPosition: 'right back',
		thirdPosition: 'centre back',
	},
	{
		name: 'Andrew',
		gender: 'M',
		position: 'goalie',
		secondPosition: 'centre back',
		thirdPosition: '',
	},
	{
		name: 'Omar',
		gender: 'M',
		position: 'midfielder',
		secondPosition: 'right winger',
		thirdPosition: 'left winger',
	},
	{
		name: 'Chris',
		gender: 'F',
		position: 'midfielder',
		secondPosition: 'left winger',
		thirdPosition: 'striker',
	},
	{
		name: 'Christian',
		gender: 'M',
		position: 'left winger',
		secondPosition: 'striker',
		thirdPosition: 'midfielder',
	},
	{
		name: 'Bogdan',
		gender: 'M',
		position: 'centre back',
		secondPosition: 'left back',
		thirdPosition: 'left winger',
	},
	{
		name: 'Alex',
		gender: 'M',
		position:'left winger',
		secondPosition: 'striker',
		thirdPosition: 'right back',
	},
	{
		name: 'Carlos',
		gender: 'M',
		position:'left winger',
		secondPosition: 'striker',
		thirdPosition: 'left back',
	},
	{
		name: 'Ratsel',
		gender: 'M',
		position:'striker',
		secondPosition: 'left winger',
		thirdPosition: 'right winger',
	},
	{
		name: 'Adrian',
		gender: 'M',
		position:'centre back',
		secondPosition: 'left winger',
		thirdPosition: 'striker',
	},
	{
		name: 'Daniel',
		gender: 'M',
		position:'centre back',
		secondPosition: 'left winger',
		thirdPosition: 'striker',
	},
	{
		name: 'John',
		gender: 'M',
		position:'right back',
		secondPosition: 'centre back',
		thirdPosition: 'right winger',
	},
	{
		name: 'Josh',
		gender: 'M',
		position:'midfielder',
		secondPosition: 'left winger',
		thirdPosition: 'right winger',
	},
	{
		name: 'Nicolas',
		gender: 'M',
		position:'centre back',
		secondPosition: 'left back',
		thirdPosition: 'left winger',
	},
	{
		name: 'Julian',
		gender: 'M',
		position:'right wing',
		secondPosition: 'striker',
		thirdPosition: 'goalie',
	},
	{
		name: 'Sanjay',
		gender: 'M',
		position:'left winger',
		secondPosition: 'striker',
		thirdPosition: 'midfielder',
	},
	{
		name: 'Nuno',
		gender: 'M',
		position: 'goalie',
		secondPosition: '',
		thirdPosition: '',
	},
	// {
	// 	name: 'Emily',
	// 	gender: 'F',
	// 	position: 'right back',
	// 	secondPosition: 'left back',
	// 	thirdPosition: '',
	// 	availability: [...gameDates]
	// },
	// {
	// 	name: 'Rakhee',
	// 	gender: 'F',
	// 	position: 'striker',
	// 	secondPosition: 'left back',
	// 	thirdPosition: 'right back',
	// 	availability: gameDates.slice(0, -1)
	// },
];

export default players;